name: nvelocity
favicon: null
layout_spectrum: 0.3839869648218155
typography_spectrum: 0.42192279594019055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#003768'
    - '#f0b310'
    - '#b7c6d4'
    - '#4f7597'
  brandStrength: 0.8654109081253409
  lightness: 0.6124358905944973
  saturation: 0.1875
  rhythmicContrast: 0.47321688872762024
purpose: []
